name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with pytest
      run: |
        pip install pytest
    - name: Deploy artifact
      run: |
        python -c "print('Mock Deployment!')"
